title: News | JoinRave.com
timezone: Asia/Yerevan
markdown: kramdown

include: ['_news']
permalink: /news/:title/

defaults:
  - scope:
      path: '_news'
    values:
      layout: default
  - scope:
      path: '_news'
    values:
      layout: default

exclude:
  - vendor # Avoid Jekyll mistakenly read the vendor directory on Travis-CI's VM .
  - Gemfile.lock
  - Gemfile
  - tools
  - README.md
