title: News | JoinRave.com
timezone: Asia/Yerevan
markdown: kramdown

include: ['_news']
permalink: /news/:title/

collections:
  pages:
    output: true
    permalink: /:name
  news:
    output: true
    permalink: /news/:title

defaults:
  - scope:
      path: '_news'
    values:
      layout: default
  - scope:
      path: ''
      type: 'news'
    values:
      layout: newsitem

exclude:
  - vendor # Avoid Jekyll mistakenly read the vendor directory on Travis-CI's VM .
  - Gemfile.lock
  - Gemfile
  - tools
  - README.md
